# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    #


services:
    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{google: google_id}]



    fastconfer.admin.conference:
        class: AppBundle\Admin\ConferenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Conference", label: "Conference" }
        arguments:
            - ~
            - AppBundle\Entity\Conference
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.inscription'] ]
            - [ setTemplate, [inner_list_row, Organization/CRUD/inner_list_conference.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    fastconfer.admin.inscription:
        class: AppBundle\Admin\InscriptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - AppBundle\Entity\Inscription
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.article'] ]
            - [ setTemplate, [inner_list_row, Organization/CRUD/inner_list_inscription.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    fastconfer.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - AppBundle\Entity\Article
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.articlereview'] ]
            - [ setTemplate, [inner_list_row, Organization/CRUD/inner_list_articles.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]


    fastconfer.admin.articlereview:
        class: AppBundle\Admin\ArticleReviewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - AppBundle\Entity\ArticleReview
            - ~

    fastconfer.admin.reviewer:
        class: AppBundle\Admin\ReviewerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - AppBundle\Entity\Reviewer
            - ~