services:
    fastconfer.user.provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{sir: sir_id}]

    fastconfer.security.conference_manager:
        class: AppBundle\Security\Manager\ConferenceManager

#    fastconfer.security.voter.conference:
#        class: AppBundle\Security\Voter\ConferenceVoter
#        public: false
#        arguments: [@fastconfer.security.conference_manager]
#        tags:
#            - { name: security.voter }

#    fastconfer.security.voter.admin:
#        class: AppBundle\Security\Voter\AdminVoter
#        public: false
#        tags:
#            - { name: security.voter }

    fastconfer.security.article_review.download.voter:
        class: AppBundle\Security\Voter\ArticleReviewDownloadVoter
        public: false
        tags:
            - { name: security.voter }

    fastconfer.security.article.voter:
        class: AppBundle\Security\Voter\ArticleVoter
        public: false
        tags:
          - { name: security.voter }

    fastconfer.security.handler.voter:
        class: AppBundle\Security\Handler\VoterSecurityHandler
        arguments: [@security.authorization_checker, ['ROLE_SUPER_ADMIN']]

    # FORMULARIOS

    fastconfer.type.topics_text:
        class: AppBundle\Form\Type\TopicsTextType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: topics_text }

    # SONATA ADMIN

    fastconfer.admin.conference:
        class: AppBundle\Admin\ConferenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Conference", label: "Conference" }
        arguments:
            - ~
            - AppBundle\Entity\Conference
            - ~
        calls:
            - [ setTemplate, [inner_list_row, backend/Conference/CRUD/inner_list_row.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    fastconfer.admin.inscription:
        class: AppBundle\Admin\InscriptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "Inscription" }
        arguments:
            - ~
            - AppBundle\Entity\Inscription
            - ~

    fastconfer.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "Article" }
        arguments:
            - ~
            - AppBundle\Entity\Article
            - ~
        calls:
            - [ addChild, ['@fastconfer.admin.reviewer'] ]
            - [ addChild, ['@fastconfer.admin.articlereview'] ]
            - [ setTemplate, [show, backend/Article/CRUD/show_article.html.twig]]


    fastconfer.admin.articlereview:
        class: AppBundle\Admin\ArticleReviewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "Article Reviews" }
        arguments:
            - ~
            - AppBundle\Entity\ArticleReview
            - AppBundle:Backend\ArticleReview

    fastconfer.admin.reviewer:
        class: AppBundle\Admin\ReviewerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "reviewer" }
        arguments:
            - ~
            - AppBundle\Entity\Reviewer
            - ~

    fastconfer.admin.reviewcomments:
        class: AppBundle\Admin\ReviewCommentsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "reviewComments" }
        arguments:
            - ~
            - AppBundle\Entity\ReviewComments
            - ~

    # LISTENER

    fastconfer.listener.current_conference:
        class: AppBundle\EventListener\CurrentConferenceListener
        arguments: [@fastconfer.security.conference_manager, @doctrine.orm.entity_manager, %site_base%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    fastconfer.listener.assignReviewerEvent:
        class: AppBundle\Main\EventListener\AssignReviewerSubscriber
        arguments: [ @mailer, @logger, @templating ]
        tags:
            - { name: kernel.event_subscriber }

    fastconfer.listener.stateEndEvent:
        class: AppBundle\Main\EventListener\StateEndSubscriber
        arguments: [ @mailer, @logger, @templating]
        tags:
            - { name: kernel.event_subscriber }

    #TWIG

    fastconfer.twig.conferenceextension:
        class: AppBundle\Twig\ConferenceExtension
        arguments: [ @router ]
        public: false
        tags:
           - { name: twig.extension }