# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    #


services:
    fastconfer.user.provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{google: google_id}]

    fastconfer.type.topics_text:
        class: AppBundle\Form\Type\TopicsTextType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: topics_text }

    fastconfer.admin.conference:
        class: AppBundle\Admin\ConferenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Conference", label: "Conference" }
        arguments:
            - ~
            - AppBundle\Entity\Conference
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.inscription'] ]
            - [ setTemplate, [inner_list_row, Organization/CRUD/inner_list_conference.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    fastconfer.admin.inscription:
        class: AppBundle\Admin\InscriptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "Inscription" }
        arguments:
            - ~
            - AppBundle\Entity\Inscription
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.article'] ]
            - [ setTemplate, [inner_list_row, Organization/CRUD/inner_list_inscription.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    fastconfer.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "article" }
        arguments:
            - ~
            - AppBundle\Entity\Article
            - ~
        calls:
            - [addChild, ['@fastconfer.admin.articlereview'] ]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [ setTemplate, [show,Organization/CRUD/show_article.html.twig]]


    fastconfer.admin.articlereview:
        class: AppBundle\Admin\ArticleReviewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "articleReview" }
        arguments:
            - ~
            - AppBundle\Entity\ArticleReview
            - ~

    fastconfer.admin.reviewer:
        class: AppBundle\Admin\ReviewerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "reviewer" }
        arguments:
            - ~
            - AppBundle\Entity\Reviewer
            - ~

    fastconfer.admin.reviewcomments:
        class: AppBundle\Admin\ReviewCommentsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "default", label: "reviewComments" }
        arguments:
            - ~
            - AppBundle\Entity\ReviewComments
            - ~
#
#    fastconfer.listener.assign_events_reviewer:
#        class: AppBundle\m