sonata_admin:
    title:      Fastconfer
    title_logo: logo.ico

    security:
#        handler: fastconfer.security.handler.voter
        handler: sonata.admin.security.handler.role

    templates:
        layout: backend/standard_layout.html.twig

    dashboard:
        groups:
            fastconfer.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

            fastconfer.admin.group.conferences:
                label:           Conferences
                label_catalogue: messages
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - fastconfer.admin.conference
                    - fastconfer.admin.inscription
                    - fastconfer.admin.article
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br /> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):