sonata_user:
    security_acl: false
    manager_type: orm

    class:
         user:         AppBundle\Entity\User
         group:        AppBundle\Entity\Group

    admin:
        user:
            class: AppBundle\Admin\UserAdmin
        group:
            class: AppBundle\Admin\GroupAdmin