sonata_admin:
    title:      Fastconfer
#    title_logo: bundles/sonataadmin/a.ico

    security:
#        handler: fastconfer.security.handler.voter
        handler: sonata.admin.security.handler.role

    templates:
        layout: backend/standard_layout.html.twig

    dashboard:
        groups:
            fastconfer.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

            fastconfer.admin.group.conferences:
                label:           Conferences
                label_catalogue: messages
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - fastconfer.admin.conference
                    - fastconfer.admin.inscription
                    - fastconfer.admin.article
